### PR TITLE
Add github issue templates to ease issue triage

### PR DESCRIPTION
**Pull request by brucellino**
This adds two templates to help in guiding those wishing to use the repo. An attempt has been made to provide bilingual (ITA/ENG) comments in two issue types. These may be customised and enhanced according to need.

### CODE REVIEW

**Comment by miccoli** [comment]
Just my personal opinion: do not use flags (which represent nations) for languages. This is an official repo form the Italian government, so using the USA flag for the english language is not appropriate.

**Comment by miccoli** [comment]
There is also another question to be answered: is this the correct place for raising issues on the graphical web tracker at http://arcg.is/C1unv ?

If so specific templates for the gis dashboard should be added.

**Comment by brucellino** [comment]
@miccoli I agree with the suggestion to not use flag emojis as substitutes for language preference (it was just adopted from the initial work by @natydev)

As for the ArcGIS dashoard - I would tend to agree that raising issues here against it would be a good idea - it would be incorporated into either the error template, or the request template, just adding the checkbox option for the dashboard in the template.

**Comment by umbros** [comment]
Grazie @brucellino e @miccoli per il contributo

**Pull request merged**
