### PR TITLE
added regione-per-regione

### PR DESCRIPTION
**Pull request by tetrapharmakon**

### CODE REVIEW

**Comment by brucellino** [comment]
@tetrapharmakon can you explain how these files were generated? Is there a script which could perhaps be added to the repo to reproduce this?

**Comment by tetrapharmakon** [comment]
Sure; without knowing which script generated the other csv's I just took [dati-regioni](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv) and wrote five lines of wolfram (I wanted to easily plot, fit and fiddle with the resulting data).

I see no point in publishing them now (they're pretty dirty); but perhaps you can tell me what language is used? Python? JS? Something else?

**Comment by brucellino** [comment]
The important thing is to maintain provenance, not criticise your or anybody's code :grin: - so no matter how dirty, if you have code which generated data, it should be published along with that data, else we have no way of knowing how the produced data set was derived from the original.

IMHO the same goes for the _actual_ data set of this repo - the primary source. There is inevitably some data cleaning done.  I'm sure that when the situation is calm they will be able to publish the protocol whereby they publish the nightly data results.

I think the best thing to do for the present moment is to let the DPC do their work, without making assumptions about how the data sets are arrived at, but wherever possible support their team in data analysis. When this includes enriching data or highlighting discrepancies in the data, those enrichments or discrepancies should be objectively demonstrable.

**Comment by tetrapharmakon** [comment]
You're right.

I added a short python file `fetch_reg.py` to fetch the data, and a new folder that collects a bunch of json files generated by `fetch_reg.py`

**Comment by umbros** [comment]
Thank you @tetrapharmakon and @brucellino we are improving all data

**Pull request closed without merging**
